httpd:
  build: .
  links:
    - maria_db:db
  ports:
    - 8180:80
  volumes:
    - ./mediawiki:/var/www/html
  environment:
     MYSQL_ROOT_PASSWORD: docker
maria_db:
  container_name: mariadb
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: docker
  ports:
    - 3306:3306
  expose:
    - "3306"
